name: leveling-up
favicon: null
layout_spectrum: 0.06080711237154901
typography_spectrum: 0.25433
title: leveling-up
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040809'
    - '#005fa3'
    - '#aabdcb'
    - '#8d4e07'
  brandStrength: 0.8900149955879897
  lightness: 0.10431300778873265
  saturation: 0.9376119929365814
  rhythmicContrast: 0.07950858888216317
purpose: []
